### ISSUE TITLE
Ссылки на следующие\предыдущие статьи

### ISSUE THREAD

**Issue by yashelter** [mai-806/fund-wiki#1]
Предлагаю добавить в конце и начале статей **_("dayXX")_** - ссылки на предыдущие и следующие соответственно

>  ("day1" <--> "day2" <--> "day3" ...)

**Comment by box1t** [comment]
Хорошая идея, сделаем )

**Comment by box1t** [comment]
я вот думал как раз, как удобнее всего это сделать и не выдумывать лишнего.
самый удачный вариант в принципе

**Comment by yashelter** [comment]
> я думал как раз, как удобнее всего это сделать и не усложнять. этот вариант самый удачный в принципе

), Также, от неизвестного мне автора вчера попался файл с доп инфой по вопросам и коллективно сделанные(писавшими) билеты, можешь использовать.
[билеты зайка 2023.docx](https://github.com/mai-806/fund-wiki/files/10474102/2023.docx)
[зайка2.0.docx](https://github.com/mai-806/fund-wiki/files/10474103/2.0.docx)

**Comment by yashelter** [comment]
Да и вообще я могу помочь с заполнением/дополнением если есть нужда)

**Comment by box1t** [comment]
А напиши мне в телегу, там пообщаемся)
Ссылка в профиле
